version : '3'
services:
  service-back:
    image: vicboni123/tp2:0.1
    environment:
      - ENVIRONMENT=python:3-alpine
#    volumes:
#      - "./logs:/logs"

  service-front:
    image: vicboni123/tp2.sfront:0.1
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - WS_BACK_URL=backend
    links:
 - "back-service:backend"
